# ----
# Site

title: MidasTouch - GitDoc
url: "https://MidasTouch-MT.github.io"
baseurl:
show_full_navigation: true

# Values for the jekyll-seo-tag gem (https://github.com/jekyll/jekyll-seo-tag)
logo: /siteicon.png
description: Open-source documentation website hosted on GitHub Pages.
author:
  name: Midas Touch
  email: midastouch@duck.com
social:
  name: Documentation
  links:
    - https://github.com/MidasTouch-MT/MidasTouch-MT.github.io

# -----
# Build

timezone: EST/UTC

permalink: pretty

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE.txt

collections:
  docs:
    title: Documentation
    permalink: /:path/
    output: true

defaults:
  -
    scope:
      path: ""
    values:
      layout: default
  -
    scope:
      path: ""
      type: "docs"
    values:
      seo:
        type: Article
      _comments:
        category: Group navigation links with this field
        order: Used to sort links in the navigation
      _options:
        content:
          width: 800
          height: 2000
  -
    scope:
      path: ""
      type: "posts"
    values:
      _comments:
        type: Marks the impact of this release

# -----------

types:
  - minor
  - major
